version: '3'
services:
#---------------------------- ZOOKEEPER ----------------------------#
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        ports:
            - 2181:2181
        networks: 
            - internal
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
#-------------------------------------------------------------------#
#------------------------------ KAFKA ------------------------------#
    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        ports:
            - 9092:9092
            - 9094:9094
        networks: 
            - internal
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9094,OUTSIDE://localhost:9092
            - KAFKA_LISTENERS=INSIDE://:9094,OUTSIDE://:9092
            - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CREATE_TOPICS="football:1:1"
        depends_on:
            - zookeeper
#-------------------------------------------------------------------#
#----------------------------- FLUME -------------------------------#
    flume:
        build: ./flume
        image: flume
        container_name: flume
        networks: 
            - internal
        depends_on:
            - sftp
            - kafka
#-------------------------------------------------------------------#
#------------------------- ELASSTICSEARCH --------------------------#
    elasticsearch:
        image: elasticsearch:7.12.1
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - ./volume/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks: 
            - internal
#-------------------------------------------------------------------#
#------------------------------ KIBANA -----------------------------#
    kibana:
        container_name: kibana
        image: kibana:7.12.1
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports: 
            - 5601:5601
        depends_on: 
            - elasticsearch
        networks: 
            - internal
#-------------------------------------------------------------------#
#------------------------------ SFTP -------------------------------#
    sftp:
        image: atmoz/sftp:latest
        container_name: sftp
        volumes:
            - ./volume/sftp:/home/sftp
        ports:
            - 2222:22
        networks: 
            - external
            - internal
        command: sftp:sftp:1001
#-------------------------------------------------------------------#
#------------------------------ MYSQL ------------------------------#
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - 3306:3306
        networks: 
            - internal
        environment:
            MYSQL_ROOT_PASSWORD: 123456
#-------------------------------------------------------------------#
#------------------------- EVENT GENERATOR -------------------------#
    eventgen:
        build: ./eventgen
        image: eventgen
        container_name: eventgenerator
        networks: 
            - internal
        depends_on: 
            - sftp
            - mysql
            - flume
        environment: 
            - SFTP_HOST=sftp
            - SFTP_USER=sftp
            - SFTP_PASSWORD=sftp
            - SFTP_PORT=22
            - OUTPUT_PREFIX=FOOTBALL_EVENTS
            - FILE_ELEMENT=5
            - INPUT_FILE=event_test.csv
#-------------------------------------------------------------------#
#----------------------------- NETWORKS ----------------------------#    
networks: 
    external: 
        name: external_network
        driver: bridge
        ipam: 
            config: 
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1
    internal: 
        name: internal_network
        driver: bridge
        ipam: 
            config: 
                - subnet: 10.6.0.0/16
                  gateway: 10.6.0.1
#-------------------------------------------------------------------#
